#### 1. Dataframe basics

#### 1.1. Import pandas and reffered the package as pd + Load "telecom_churn.csv" and assign in to the variable df <span style= color:#0033cc>(3 points)</span>

In [3]:
pip install pandas

Collecting pandasNote: you may need to restart the kernel to use updated packages.

  Using cached pandas-2.2.1-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy<2,>=1.22.4 in c:\python310\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\python310\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\python310\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached pandas-2.2.1-cp310-cp310-win_amd64.whl (11.6 MB)
Installing collected packages: pandas
Successfully installed pandas-2.2.1

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv("telecom_churn.csv")

In [7]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

#### 1.2 Return the column labels/names <span style= color:#0033cc>(2 points)</span>

In [8]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77,26.55,215.5,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,No,No,0,231.1,57,39.29,153.4,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,No,No,0,180.8,109,30.74,288.8,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [9]:
df. columns. values. tolist()

['State',
 'Account length',
 'Area code',
 'International plan',
 'Voice mail plan',
 'Number vmail messages',
 'Total day minutes',
 'Total day calls',
 'Total day charge',
 'Total eve minutes',
 'Total eve calls',
 'Total eve charge',
 'Total night minutes',
 'Total night calls',
 'Total night charge',
 'Total intl minutes',
 'Total intl calls',
 'Total intl charge',
 'Customer service calls',
 'Churn']

#### 1.3 Print the df shape <span style= color:#0033cc>(3 points)</span>

In [10]:
df.shape

(3333, 20)

#### 2. What is the total day calls given by state and area code?

#### 2.1 Group the df by state and area code (assign it to grouped variable). <span style= color:#0033cc>(5 points)</span>

In [16]:
df.groupby('Area code')

In [15]:
df.groupby('State')

In [17]:
df.groupby(['State','Area code'])

#### 2.2 Use agg with the desired function sum to get the final answer (assign it to telecom_agg variable).<span style= color:#0033cc>(5 points)</span>

In [19]:
eggg=df.groupby(['State','Area code'])

In [27]:
df.agg(sum)

C:\Users\huser\AppData\Local\Temp\ipykernel_12504\3026864763.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrame.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.agg(sum)

State                     KSOHNJOHOKALMAMOLAWVINRIIAMTIANYIDVTVATXFLCOAZ...
Account length                                                       336849
Area code                                                           1457129
International plan        NoNoNoYesYesYesNoYesNoYesNoNoNoNoNoNoNoNoNoNoN...
Voice mail plan           YesYesNoNoNoNoYesNoNoYesNoNoNoNoNoNoYesNoYesNo...
Number vmail messages                                                 26994
Total day minutes                                                  599190.4
Total day calls                                                      334752
Total day charge                                                  101864.17
Total eve minutes                                                  669867.5
Total eve calls                                                      333681
Total eve charge                                                   56939.44
Total night minutes                                                669506.5
Total night calls                                                    333659
Total night charge                                                 30128.07
Total intl minutes                                                  34120.9
Total intl calls                                                      14930
Total intl charge                                                   9214.35
Customer service calls                                                 5209
Churn                                                                   483
dtype: object

In [28]:
df.agg(sum)['Total day minutes']

C:\Users\huser\AppData\Local\Temp\ipykernel_12504\3348553378.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrame.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.agg(sum)['Total day minutes']

599190.3999999999

#### 2.3 Reset the group by index <span style= color:#0033cc>(3 points)</span>

In [29]:
df. reset_index()

,index,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,0,KS,128,415,No,Yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,1,OH,107,415,No,Yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,2,NJ,137,415,No,No,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,3,OH,84,408,Yes,No,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,4,OK,75,415,Yes,No,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,3328,AZ,192,415,No,Yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,3329,WV,68,415,No,No,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,3330,RI,28,510,No,No,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,3331,CT,184,510,Yes,No,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,3332,TN,74,415,No,Yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

#### 2.4 Use head function to review the first 10 telecom_agg rows <span style= color:#0033cc>(3 points)</span>

In [30]:
df.agg(sum).head(10)

C:\Users\huser\AppData\Local\Temp\ipykernel_12504\4247650807.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrame.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.agg(sum).head(10)

State                    KSOHNJOHOKALMAMOLAWVINRIIAMTIANYIDVTVATXFLCOAZ...
Account length                                                      336849
Area code                                                          1457129
International plan       NoNoNoYesYesYesNoYesNoYesNoNoNoNoNoNoNoNoNoNoN...
Voice mail plan          YesYesNoNoNoNoYesNoNoYesNoNoNoNoNoNoYesNoYesNo...
Number vmail messages                                                26994
Total day minutes                                                 599190.4
Total day calls                                                     334752
Total day charge                                                 101864.17
Total eve minutes                                                 669867.5
dtype: object

#### 3. Users Churn rate

#### 3.1 Change "Churn" column type to an integer: <span style= color:#0033cc>(3 points)</span>

In [32]:
pd.to_numeric(df[ "Churn"])

0       False
1       False
2       False
3       False
4       False
        ...
3328    False
3329    False
3330    False
3331    False
3332    False
Name: Churn, Length: 3333, dtype: bool

#### 3.2 what is the users "churn rate" in our dataframe? <span style= color:#0033cc>(5 points)</span>
Hint: the churn rate formula can be calculated as the "number of churned" divided by the "total number of customers".

In [34]:
pd.agg(sum)["number of churned"]/pd.agg(sum)["total number of customers"]

AttributeError: module 'pandas' has no attribute 'agg'

#### 3.3  How the charn rate can affect on the company? <span style= color:#0033cc>(3 points)</span>

In [113]:
df.corr()['Account length'].sort_values()

ValueError: could not convert string to float: 'KS'

#### 3.4 How much time (on average) do churned users spend on the phone during daytime? <span style= color:#0033cc>(5 points)</span>
Hint: filter churn column when the value of churn equal to 1

In [37]:
df.sum()['Total day minutes']

599190.3999999999

#### 3.5 What is the maximum length of international calls among loyal users who do not have an international plan? ('International plan' == 'No') <span style= color:#0033cc>(5 points)</span>
Hint: 2 filters conditions,churn equal to 0 and international plan equal to no

In [40]:
df[df['International plan']=='No']['Total intl minutes'].max()

18.9

#### 4. Select top 3 international plan subscribers and non subscribers with the most intl calls

In [45]:
df[df['International plan']=='No'].sort_values('Total intl calls',ascending=False).head(3)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
22,AZ,130,415,No,No,0,183.0,112,31.11,72.9,99,6.20,181.8,78,8.18,9.5,19,2.57,0,False
377,ND,79,408,No,No,0,205.7,123,34.97,214.5,108,18.23,226.1,106,10.17,6.7,18,1.81,1,False
982,ND,84,415,No,Yes,33,159.1,106,27.05,149.8,101,12.73,213.4,108,9.60,13.0,18,3.51,1,False

In [46]:
df[df['International plan']=='Yes'].sort_values('Total intl calls',ascending=False).head(3)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3291,MI,119,510,Yes,Yes,22,172.1,119,29.26,223.6,133,19.01,150.0,94,6.75,13.9,20,3.75,1,True
41,MD,135,408,Yes,Yes,41,173.1,85,29.43,203.9,107,17.33,122.2,78,5.50,14.6,15,3.94,0,True
957,NV,144,415,Yes,No,0,150.0,69,25.50,285.9,73,24.30,190.6,121,8.58,9.4,15,2.54,0,False

#### 4.1. Build a function top which attributes df, n (for the top n) and column. In this function use sort_values to sort the values in the column specified. <span style= color:#0033cc>(10 points)</span>
Note: Do not apply the function on the whole data frame (e.i. top(df, n=3)) as the output will be the top 3 regardless of subscribers and non-subscribers.

In [47]:
df[df['International plan']=='Yes'].sort_values('Total intl calls',ascending=False).head(3)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3291,MI,119,510,Yes,Yes,22,172.1,119,29.26,223.6,133,19.01,150.0,94,6.75,13.9,20,3.75,1,True
41,MD,135,408,Yes,Yes,41,173.1,85,29.43,203.9,107,17.33,122.2,78,5.50,14.6,15,3.94,0,True
957,NV,144,415,Yes,No,0,150.0,69,25.50,285.9,73,24.30,190.6,121,8.58,9.4,15,2.54,0,False

#### 4.2. Group the df dataframe by 'International plan' and use apply(top) to apply this function. <span style= color:#0033cc>(5 points)</span>

In [52]:
df.groupby('International plan').apply(max)

C:\Users\huser\AppData\Local\Temp\ipykernel_12504\3731629920.py:1: FutureWarning: The provided callable <built-in function max> is currently using np.maximum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.maximum.reduce instead.
  df.groupby('International plan').apply(max)
C:\Users\huser\AppData\Local\Temp\ipykernel_12504\3731629920.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('International plan').apply(max)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
International plan,,,,,,,,,,,,,,,,,,,,
No,WY,243,510,No,Yes,51,350.8,165,59.64,361.8,170,30.75,395.0,175,17.77,18.9,19,5.1,9,True
Yes,WY,224,510,Yes,Yes,45,346.8,146,58.96,363.7,159,30.91,352.5,154,15.86,20.0,20,5.4,9,True

#### 5. pd.crosstab

#### 5.1 how the observations in our sample are normalized (divide each value by the sum of the values) in the context of two variables - Churn and Voice mail plan. To do so, build a contingency table using the crosstab method. <span style= color:#0033cc>(6 points)</span>
Hint: To normalize using all values, simply set normalize=True

In [64]:
c=pd.crosstab(df['Churn'],df['Voice mail plan'])
c

Voice mail plan    No  Yes
Churn
False            2008  842
True              403   80

#### 5.2 What is the conclustion of most of users regarding voice mail usage? <span style= color:#0033cc>(4 points)</span>

In [62]:
df[df['Voice mail plan']=='No'].count()

State                     2411
Account length            2411
Area code                 2411
International plan        2411
Voice mail plan           2411
Number vmail messages     2411
Total day minutes         2411
Total day calls           2411
Total day charge          2411
Total eve minutes         2411
Total eve calls           2411
Total eve charge          2411
Total night minutes       2411
Total night calls         2411
Total night charge        2411
Total intl minutes        2411
Total intl calls          2411
Total intl charge         2411
Customer service calls    2411
Churn                     2411
dtype: int64

In [77]:
c.sum().idxmax()

'No'

#### 6. Columns calculations

#### 6.1 Add a column name 'total_charge', and get the total charge by sum all the charge columns <span style= color:#0033cc>(7 points)</span>

In [94]:
df=df.assign(total_charge=df['Total day charge']+df['Total eve charge']+df['Total night charge']+df['Total intl charge'])
df

,State,Account length,Area code,is_expensive,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,total_charge
0,KS,128,415,True,No,Yes,25,265.1,110,45.07,...,16.78,244.7,91,11.01,10.0,3,2.70,1,False,75.56
1,OH,107,415,True,No,Yes,26,161.6,123,27.47,...,16.62,254.4,103,11.45,13.7,3,3.70,1,False,59.24
2,NJ,137,415,True,No,No,0,243.4,114,41.38,...,10.30,162.6,104,7.32,12.2,5,3.29,0,False,62.29
3,OH,84,408,True,Yes,No,0,299.4,71,50.90,...,5.26,196.9,89,8.86,6.6,7,1.78,2,False,66.80
4,OK,75,415,True,Yes,No,0,166.7,113,28.34,...,12.61,186.9,121,8.41,10.1,3,2.73,3,False,52.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,True,No,Yes,36,156.2,77,26.55,...,18.32,279.1,83,12.56,9.9,6,2.67,2,False,60.10
3329,WV,68,415,True,No,No,0,231.1,57,39.29,...,13.04,191.3,123,8.61,9.6,4,2.59,3,False,63.53
3330,RI,28,510,True,No,No,0,180.8,109,30.74,...,24.55,191.9,91,8.64,14.1,6,3.81,2,False,67.74
3331,CT,184,510,True,Yes,No,0,213.8,105,36.35,...,13.57,139.2,137,6.26,5.0,10,1.35,2,False,57.53
3332,TN,74,415,True,No,Yes,25,234.4,113,39.85,...,22.60,241.4,77,10.86,13.7,4,3.70,0,False,77.01

####  6.2 Add a column name 'Day_charge_pct', and get day charge precentage of total charge by dividing the column 'Total day charge' by the column 'total_charge'. <span style= color:#0033cc>(7 points)</span>

In [95]:
df.assign(Day_charge_pct=df['Total day charge']/df['total_charge'])

,State,Account length,Area code,is_expensive,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,...,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,total_charge,Day_charge_pct
0,KS,128,415,True,No,Yes,25,265.1,110,45.07,...,244.7,91,11.01,10.0,3,2.70,1,False,75.56,0.596480
1,OH,107,415,True,No,Yes,26,161.6,123,27.47,...,254.4,103,11.45,13.7,3,3.70,1,False,59.24,0.463707
2,NJ,137,415,True,No,No,0,243.4,114,41.38,...,162.6,104,7.32,12.2,5,3.29,0,False,62.29,0.664312
3,OH,84,408,True,Yes,No,0,299.4,71,50.90,...,196.9,89,8.86,6.6,7,1.78,2,False,66.80,0.761976
4,OK,75,415,True,Yes,No,0,166.7,113,28.34,...,186.9,121,8.41,10.1,3,2.73,3,False,52.09,0.544058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,True,No,Yes,36,156.2,77,26.55,...,279.1,83,12.56,9.9,6,2.67,2,False,60.10,0.441764
3329,WV,68,415,True,No,No,0,231.1,57,39.29,...,191.3,123,8.61,9.6,4,2.59,3,False,63.53,0.618448
3330,RI,28,510,True,No,No,0,180.8,109,30.74,...,191.9,91,8.64,14.1,6,3.81,2,False,67.74,0.453794
3331,CT,184,510,True,Yes,No,0,213.8,105,36.35,...,139.2,137,6.26,5.0,10,1.35,2,False,57.53,0.631844
3332,TN,74,415,True,No,Yes,25,234.4,113,39.85,...,241.4,77,10.86,13.7,4,3.70,0,False,77.01,0.517465

#### 7. Day charge percentage and state visualization

#### 7.1 Import matplotlib.pyplot and referred the package as plt <span style= color:#0033cc>(2 points)</span>

In [98]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.
Collecting matplotlib
  Downloading matplotlib-3.8.3-cp310-cp310-win_amd64.whl.metadata (5.9 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.2.0-cp310-cp310-win_amd64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.49.0-cp310-cp310-win_amd64.whl.metadata (162 kB)
     ---------------------------------------- 0.0/162.3 kB ? eta -:--:--
     --------- --------------------------- 41.0/162.3 kB 991.0 kB/s eta 0:00:01
     ------------------- ------------------- 81.9/162.3 kB 1.6 MB/s eta 0:00:01
     -------------------------------------- 162.3/162.3 kB 1.4 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.5-cp310-cp310-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: numpy<2,>=1.21 in c:\python310\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\python310\lib\site-packages (from matplotlib) (23.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-10.2.0-cp310-cp310-win_amd64.whl.metadata (9.9 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\python310\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Downloading matplotlib-3.8.3-cp310-cp310-win_amd64.whl (7.6 MB)
   ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
    --------------------------------------- 0.1/7.6 MB 1.5 MB/s eta 0:00:06
   - -------------------------------------- 0.3/7.6 MB 2.0 MB/s eta 0:00:04
   -- ------------------------------------- 0.4/7.6 MB 2.4 MB/s eta 0:00:03
   --- ------------------------------------ 0.6/7.6 MB 2.9 MB/s eta 0:00:03
   ---- ----------------------------------- 0.8/7.6 MB 3.1 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/7.6 MB 3.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/7.6 MB 3.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/7.6 MB 2.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.1/7.6 MB 2.5 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/7.6 MB 2.7 MB/s eta 0:00:03
   ------- -------------------------------- 1.5/7.6 MB 2.8 MB/s eta 0:00:03
   -------- ------------------------------- 1.5/7.6 MB 2.6 MB/s eta 0:00:03
   -------- ------------------------------- 1.7/7.6 MB 2.7 MB/s eta 0:00:03
   --------- ------------------------------ 1.7/7.6 MB 2.7 MB/s eta 0:00:03
   --------- ------------------------------ 1.7/7.6 MB 2.5 MB/s eta 0:00:03
   --------- ------------------------------ 1.7/7.6 MB 2.5 MB/s eta 0:00:03
   --------- ------------------------------ 1.7/7.6 MB 2.5 MB/s eta 0:00:03
   --------- ------------------------------ 1.7/7.6 MB 2.5 MB/s eta 0:00:03
   --------- ------------------------------ 1.7/7.6 MB 2.5 MB/s eta 0:00:03
   --------- ------------------------------ 1.8/7.6 MB 1.8 MB/s eta 0:00:04
   ---------- ----------------------------- 1.9/7.6 MB 1.9 MB/s eta 0:00:03
   ----------- ---------------------------- 2.2/7.6 MB 2.1 MB/s eta 0:00:03
   ------------ --------------------------- 2.4/7.6 MB 2.2 MB/s eta 0:00:03
   -------------- ------------------------- 2.7/7.6 MB 2.3 MB/s eta 0:00:03
   --------------- ------------------------ 2.9/7.6 MB 2.4 MB/s eta 0:00:02
   ---------------- ----------------------- 3.1/7.6 MB 2.5 MB/s eta 0:00:02
   ----------------- ---------------------- 3.3/7.6 MB 2.6 MB/s eta 0:00:02
   ------------------ --------------------- 3.5/7.6 MB 2.6 MB/s eta 0:00:02
   ------------------- -------------------- 3.7/7.6 MB 2.7 MB/s eta 0:00:02
   -------------------- ------------------- 4.0/7.6 MB 2.8 MB/s eta 0:00:02
   --------------------- ------------------ 4.2/7.6 MB 2.9 MB/s eta 0:00:02
   ----------------------- ---------------- 4.4/7.6 MB 2.9 MB/s eta 0:00:02
   ------------------------ --------------- 4.7/7.6 MB 3.0 MB/s eta 0:00:01
   ------------------------- -------------- 5.0/7.6 MB 3.1 MB/s eta 0:00:01
   --------------------------- ------------ 5.2/7.6 MB 3.2 MB/s eta 0:00:01
   ---------------------------- ----------- 5.5/7.6 MB 3.3 MB/s eta 0:00:01
   ------------------------------ --------- 5.8/7.6 MB 3.4 MB/s eta 0:00:01
   -------------------------------- ------- 6.1/7.6 MB 3.4 MB/s eta 0:00:01
   --------------------------------- ------ 6.4/7.6 MB 3.5 MB/s eta 0:00:01
   ----------------------------------- ---- 6.7/7.6 MB 3.6 MB/s eta 0:00:01
   ------------------------------------ --- 7.1/7.6 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 7.3/7.6 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  7.6/7.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 7.6/7.6 MB 3.8 MB/s eta 0:00:00
Downloading contourpy-1.2.0-cp310-cp310-win_amd64.whl (186 kB)
   ---------------------------------------- 0.0/186.7 kB ? eta -:--:--
   ------ --------------------------------- 30.7/186.7 kB ? eta -:--:--
   ------------------------ --------------- 112.6/186.7 kB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 186.7/186.7 kB 1.9 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.49.0-cp310-cp310-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   - -------------------------------------- 0.1/2.2 MB 1.7 MB/s eta 0:00:02
   - -------------------------------------- 0.1/2.2 MB 1.5 MB/s eta 0:00:02
   - -------------------------------------- 0.1/2.2 MB 1.5 MB/s eta 0:00:02
   -- ------------------------------------- 0.1/2.2 MB 722.1 kB/s eta 0:00:03
   -- ------------------------------------- 0.1/2.2 MB 774.0 kB/s eta 0:00:03
   -- ------------------------------------- 0.1/2.2 MB 774.0 kB/s eta 0:00:03
   --- ------------------------------------ 0.2/2.2 MB 590.8 kB/s eta 0:00:04
   --- ------------------------------------ 0.2/2.2 MB 590.8 kB/s eta 0:00:04
   --- ------------------------------------ 0.2/2.2 MB 541.9 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/2.2 MB 492.1 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/2.2 MB 492.1 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/2.2 MB 457.3 kB/s eta 0:00:05
   ---- ----------------------------------- 0.3/2.2 MB 425.2 kB/s eta 0:00:05
   ---- ----------------------------------- 0.3/2.2 MB 425.2 kB/s eta 0:00:05
   ----- ---------------------------------- 0.3/2.2 MB 416.0 kB/s eta 0:00:05
   ----- ---------------------------------- 0.3/2.2 MB 416.0 kB/s eta 0:00:05
   ----- ---------------------------------- 0.3/2.2 MB 368.6 kB/s eta 0:00:06
   ----- ---------------------------------- 0.3/2.2 MB 368.6 kB/s eta 0:00:06
   ----- ---------------------------------- 0.3/2.2 MB 352.3 kB/s eta 0:00:06
   ----- ---------------------------------- 0.3/2.2 MB 352.3 kB/s eta 0:00:06
   ------ --------------------------------- 0.3/2.2 MB 344.3 kB/s eta 0:00:06
   ------ --------------------------------- 0.3/2.2 MB 344.3 kB/s eta 0:00:06
   ------ --------------------------------- 0.3/2.2 MB 327.7 kB/s eta 0:00:06
   ------ --------------------------------- 0.4/2.2 MB 323.0 kB/s eta 0:00:06
   ------ --------------------------------- 0.4/2.2 MB 323.0 kB/s eta 0:00:06
   ------ --------------------------------- 0.4/2.2 MB 314.4 kB/s eta 0:00:06
   ------- -------------------------------- 0.4/2.2 MB 314.9 kB/s eta 0:00:06
   ------- -------------------------------- 0.4/2.2 MB 315.7 kB/s eta 0:00:06
   ------- -------------------------------- 0.4/2.2 MB 312.2 kB/s eta 0:00:06
   -------- ------------------------------- 0.4/2.2 MB 316.5 kB/s eta 0:00:06
   -------- ------------------------------- 0.5/2.2 MB 313.2 kB/s eta 0:00:06
   -------- ------------------------------- 0.5/2.2 MB 317.1 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.2 MB 320.9 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.2 MB 317.7 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.2 MB 324.5 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.2 MB 321.4 kB/s eta 0:00:06
   ---------- ----------------------------- 0.6/2.2 MB 324.6 kB/s eta 0:00:06
   ---------- ----------------------------- 0.6/2.2 MB 327.8 kB/s eta 0:00:05
   ---------- ----------------------------- 0.6/2.2 MB 330.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.6/2.2 MB 336.2 kB/s eta 0:00:05
   ----------- ---------------------------- 0.6/2.2 MB 333.4 kB/s eta 0:00:05
   ----------- ---------------------------- 0.6/2.2 MB 338.6 kB/s eta 0:00:05
   ------------ --------------------------- 0.7/2.2 MB 341.0 kB/s eta 0:00:05
   ------------ --------------------------- 0.7/2.2 MB 332.8 kB/s eta 0:00:05
   ------------ --------------------------- 0.7/2.2 MB 342.8 kB/s eta 0:00:05
   ------------- -------------------------- 0.7/2.2 MB 342.5 kB/s eta 0:00:05
   ------------- -------------------------- 0.7/2.2 MB 344.5 kB/s eta 0:00:05
   ------------- -------------------------- 0.7/2.2 MB 344.5 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 346.3 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 343.6 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 343.6 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 343.1 kB/s eta 0:00:05
   --------------- ------------------------ 0.8/2.2 MB 342.8 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.2 MB 340.4 kB/s eta 0:00:04
   --------------- ------------------------ 0.9/2.2 MB 340.0 kB/s eta 0:00:04
   --------------- ------------------------ 0.9/2.2 MB 337.7 kB/s eta 0:00:04
   ---------------- ----------------------- 0.9/2.2 MB 339.6 kB/s eta 0:00:04
   ---------------- ----------------------- 0.9/2.2 MB 341.3 kB/s eta 0:00:04
   ---------------- ----------------------- 0.9/2.2 MB 339.2 kB/s eta 0:00:04
   ----------------- ---------------------- 0.9/2.2 MB 340.8 kB/s eta 0:00:04
   ----------------- ---------------------- 1.0/2.2 MB 338.8 kB/s eta 0:00:04
   ----------------- ---------------------- 1.0/2.2 MB 340.4 kB/s eta 0:00:04
   ------------------ --------------------- 1.0/2.2 MB 343.8 kB/s eta 0:00:04
   ------------------ --------------------- 1.0/2.2 MB 343.7 kB/s eta 0:00:04
   ------------------ --------------------- 1.0/2.2 MB 345.0 kB/s eta 0:00:04
   ------------------- -------------------- 1.1/2.2 MB 348.2 kB/s eta 0:00:04
   ------------------- -------------------- 1.1/2.2 MB 349.5 kB/s eta 0:00:04
   ------------------- -------------------- 1.1/2.2 MB 349.3 kB/s eta 0:00:04
   -------------------- ------------------- 1.1/2.2 MB 350.6 kB/s eta 0:00:04
   -------------------- ------------------- 1.1/2.2 MB 355.1 kB/s eta 0:00:03
   --------------------- ------------------ 1.2/2.2 MB 357.8 kB/s eta 0:00:03
   --------------------- ------------------ 1.2/2.2 MB 358.9 kB/s eta 0:00:03
   ---------------------- ----------------- 1.2/2.2 MB 363.1 kB/s eta 0:00:03
   ---------------------- ----------------- 1.2/2.2 MB 365.8 kB/s eta 0:00:03
   ----------------------- ---------------- 1.3/2.2 MB 368.1 kB/s eta 0:00:03
   ----------------------- ---------------- 1.3/2.2 MB 367.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.2 MB 372.9 kB/s eta 0:00:03
   ------------------------ --------------- 1.4/2.2 MB 376.6 kB/s eta 0:00:03
   ------------------------ --------------- 1.4/2.2 MB 376.2 kB/s eta 0:00:03
   ------------------------- -------------- 1.4/2.2 MB 382.6 kB/s eta 0:00:03
   -------------------------- ------------- 1.4/2.2 MB 386.0 kB/s eta 0:00:02
   -------------------------- ------------- 1.5/2.2 MB 389.4 kB/s eta 0:00:02
   --------------------------- ------------ 1.5/2.2 MB 391.0 kB/s eta 0:00:02
   --------------------------- ------------ 1.5/2.2 MB 394.4 kB/s eta 0:00:02
   ---------------------------- ----------- 1.5/2.2 MB 398.0 kB/s eta 0:00:02
   ---------------------------- ----------- 1.6/2.2 MB 395.3 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.2 MB 402.6 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.2 MB 402.6 kB/s eta 0:00:02
   ------------------------------ --------- 1.6/2.2 MB 402.3 kB/s eta 0:00:02
   ------------------------------ --------- 1.6/2.2 MB 402.3 kB/s eta 0:00:02
   ------------------------------ --------- 1.7/2.2 MB 399.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.7/2.2 MB 399.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.7/2.2 MB 396.6 kB/s eta 0:00:02
   ------------------------------ --------- 1.7/2.2 MB 396.6 kB/s eta 0:00:02
   ------------------------------- -------- 1.7/2.2 MB 391.8 kB/s eta 0:00:02
   ------------------------------- -------- 1.7/2.2 MB 390.9 kB/s eta 0:00:02
   ------------------------------- -------- 1.7/2.2 MB 390.9 kB/s eta 0:00:02
   ------------------------------- -------- 1.7/2.2 MB 386.3 kB/s eta 0:00:02
   ------------------------------- -------- 1.7/2.2 MB 386.3 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 382.8 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 380.8 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 380.8 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 376.7 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 376.7 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.2 MB 374.8 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.2 MB 374.8 kB/s eta 0:00:02
   --------------------------------- ------ 1.8/2.2 MB 370.9 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 370.3 kB/s eta 0:00:01
   --------------------------------- ------ 1.9/2.2 MB 369.8 kB/s eta 0:00:01
   --------------------------------- ------ 1.9/2.2 MB 369.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.9/2.2 MB 367.2 kB/s eta 0:00:01
   ---------------------------------- ----- 1.9/2.2 MB 367.9 kB/s eta 0:00:01
   ---------------------------------- ----- 1.9/2.2 MB 367.9 kB/s eta 0:00:01
   ---------------------------------- ----- 1.9/2.2 MB 363.2 kB/s eta 0:00:01
   ---------------------------------- ----- 1.9/2.2 MB 363.2 kB/s eta 0:00:01
   ---------------------------------- ----- 1.9/2.2 MB 363.2 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.2 MB 358.6 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.2 MB 358.6 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.2 MB 356.1 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.2 MB 356.1 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.2 MB 350.9 kB/s eta 0:00:01
   ----------------------------------- ---- 1.9/2.2 MB 350.9 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 346.8 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 346.8 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 344.7 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 344.7 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 342.7 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 342.7 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 342.7 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 342.7 kB/s eta 0:00:01
   ------------------------------------ --- 2.0/2.2 MB 337.1 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.2 MB 334.5 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.2 MB 334.5 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.2 MB 332.7 kB/s eta 0:00:01
   ------------------------------------- -- 2.0/2.2 MB 332.7 kB/s eta 0:00:01
   ------------------------------------- -- 2.1/2.2 MB 328.5 kB/s eta 0:00:01
   ------------------------------------- -- 2.1/2.2 MB 328.5 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 328.5 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 328.5 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 326.9 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 326.9 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 324.6 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 324.6 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.2 MB 322.2 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.2 MB 321.5 kB/s eta 0:00:01
   ---------------------------------------  2.2/2.2 MB 321.5 kB/s eta 0:00:01
   ---------------------------------------  2.2/2.2 MB 321.5 kB/s eta 0:00:01
   ---------------------------------------  2.2/2.2 MB 320.9 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 318.8 kB/s eta 0:00:00
Downloading kiwisolver-1.4.5-cp310-cp310-win_amd64.whl (56 kB)
   ---------------------------------------- 0.0/56.1 kB ? eta -:--:--
   ----------------------------- ---------- 41.0/56.1 kB 960.0 kB/s eta 0:00:01
   ---------------------------------------- 56.1/56.1 kB 975.6 kB/s eta 0:00:00
Downloading pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
    --------------------------------------- 0.0/2.6 MB 991.0 kB/s eta 0:00:03
   - -------------------------------------- 0.1/2.6 MB 1.4 MB/s eta 0:00:02
   -- ------------------------------------- 0.2/2.6 MB 2.0 MB/s eta 0:00:02
   -- ------------------------------------- 0.2/2.6 MB 2.0 MB/s eta 0:00:02
   ------ --------------------------------- 0.4/2.6 MB 2.0 MB/s eta 0:00:02
   --------- ------------------------------ 0.6/2.6 MB 2.4 MB/s eta 0:00:01
   ----------- ---------------------------- 0.8/2.6 MB 2.4 MB/s eta 0:00:01
   ------------- -------------------------- 0.9/2.6 MB 2.6 MB/s eta 0:00:01
   ----------------- ---------------------- 1.1/2.6 MB 2.7 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.6 MB 2.8 MB/s eta 0:00:01
   --------------------- ------------------ 1.4/2.6 MB 2.8 MB/s eta 0:00:01
   ---------------------- ----------------- 1.5/2.6 MB 2.8 MB/s eta 0:00:01
   ------------------------ --------------- 1.6/2.6 MB 2.7 MB/s eta 0:00:01
   ------------------------- -------------- 1.7/2.6 MB 2.7 MB/s eta 0:00:01
   -------------------------- ------------- 1.7/2.6 MB 2.5 MB/s eta 0:00:01
   --------------------------- ------------ 1.8/2.6 MB 2.5 MB/s eta 0:00:01
   ----------------------------- ---------- 1.9/2.6 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 2.0/2.6 MB 2.5 MB/s eta 0:00:01
   ------------------------------- -------- 2.1/2.6 MB 2.4 MB/s eta 0:00:01
   -------------------------------- ------- 2.1/2.6 MB 2.3 MB/s eta 0:00:01
   --------------------------------- ------ 2.2/2.6 MB 2.3 MB/s eta 0:00:01
   --------------------------------- ------ 2.2/2.6 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 2.3/2.6 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 2.3/2.6 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 2.4/2.6 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 2.4/2.6 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 2.4/2.6 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 2.4/2.6 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 2.5/2.6 MB 1.9 MB/s eta 0:00:01

ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'C:\\Python310\\share\\man\\man1\\ttx.1'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [103]:
pip install --upgrade matplotlib

Collecting matplotlib
  Using cached matplotlib-3.8.3-cp310-cp310-win_amd64.whl.metadata (5.9 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.2.0-cp310-cp310-win_amd64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: fonttools>=4.22.0 in c:\python310\lib\site-packages (from matplotlib) (4.49.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\python310\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in c:\python310\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\python310\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in c:\python310\lib\site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\python310\lib\site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\python310\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Using cached matplotlib-3.8.3-cp310-cp310-win_amd64.whl (7.6 MB)
Using cached contourpy-1.2.0-cp310-cp310-win_amd64.whl (186 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Installing collected packages: cycler, contourpy, matplotlib
Successfully installed contourpy-1.2.0 cycler-0.12.1 matplotlib-3.8.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [106]:
import matplotlib.pyplot as plt

#### 7.2 create new string list with the name 'my_color' that contains the following colors names: red,green,orange,blue,yellow <span style= color:#0033cc>(4 points)</span>

In [109]:
my_colors=[ 'red','green','orange','blue','yellow' ]
my_colors

['red', 'green', 'orange', 'blue', 'yellow']

#### 7.3 Bar chart plot <span style= color:#0033cc>(10 points)</span>

1.Select first 5 rows of the dataframe (use df.iloc[])

2.Use <span style= color:blue>df.plot</span> function with kind='bar' and x='State' and y='Day_charge_pct' and color = my_colors to make a simple bar chart plot (of the day chart %).

3.Use <span style= color:blue>plt.xlabel("State Code")</span> and <span style= color:blue>plt.ylabel("Day Charge %")</span> to label the corresponding axes